"""Initial migration with all tables

Revision ID: 151c4b01e3ed
Revises: 
Create Date: 2025-12-06 23:08:23.313471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151c4b01e3ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedures',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('typical_cost_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('typical_cost_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recovery_days', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('cpt_codes', sa.JSON(), nullable=False),
    sa.Column('icd10_codes', sa.JSON(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_procedure_category', 'procedures', ['category'], unique=False)
    op.create_index('idx_procedure_name', 'procedures', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('patient_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('insurance_provider', sa.String(length=255), nullable=False),
    sa.Column('encrypted_policy_number', sa.Text(), nullable=False),
    sa.Column('group_number', sa.String(length=100), nullable=True),
    sa.Column('plan_type', sa.String(length=100), nullable=True),
    sa.Column('coverage_details', sa.JSON(), nullable=True),
    sa.Column('encrypted_medical_history', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_patient_insurance_provider', 'patient_profiles', ['insurance_provider'], unique=False)
    op.create_index('idx_patient_zip_code', 'patient_profiles', ['zip_code'], unique=False)
    op.create_table('cost_breakdowns',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('procedure_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('surgeon_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('facility_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('anesthesia_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('post_op_care', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('insurance_coverage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('patient_responsibility', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deductible', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('copay', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('out_of_pocket_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_plans', sa.JSON(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_patient', 'cost_breakdowns', ['patient_id'], unique=False)
    op.create_index('idx_cost_procedure', 'cost_breakdowns', ['procedure_id'], unique=False)
    op.create_table('profile_version_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_version_history_profile_version', 'profile_version_history', ['profile_id', 'version'], unique=False)
    op.create_table('visualization_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('procedure_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('before_image_url', sa.String(length=500), nullable=False),
    sa.Column('after_image_url', sa.String(length=500), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visualization_generated_at', 'visualization_results', ['generated_at'], unique=False)
    op.create_index('idx_visualization_patient', 'visualization_results', ['patient_id'], unique=False)
    op.create_index('idx_visualization_procedure', 'visualization_results', ['procedure_id'], unique=False)
    op.create_table('preauth_forms',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('procedure_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cost_breakdown_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('cpt_codes', sa.JSON(), nullable=False),
    sa.Column('icd10_codes', sa.JSON(), nullable=False),
    sa.Column('medical_justification', sa.Text(), nullable=False),
    sa.Column('provider_info', sa.JSON(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_breakdown_id'], ['cost_breakdowns.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_preauth_patient', 'preauth_forms', ['patient_id'], unique=False)
    op.create_index('idx_preauth_procedure', 'preauth_forms', ['procedure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_preauth_procedure', table_name='preauth_forms')
    op.drop_index('idx_preauth_patient', table_name='preauth_forms')
    op.drop_table('preauth_forms')
    op.drop_index('idx_visualization_procedure', table_name='visualization_results')
    op.drop_index('idx_visualization_patient', table_name='visualization_results')
    op.drop_index('idx_visualization_generated_at', table_name='visualization_results')
    op.drop_table('visualization_results')
    op.drop_index('idx_version_history_profile_version', table_name='profile_version_history')
    op.drop_table('profile_version_history')
    op.drop_index('idx_cost_procedure', table_name='cost_breakdowns')
    op.drop_index('idx_cost_patient', table_name='cost_breakdowns')
    op.drop_table('cost_breakdowns')
    op.drop_index('idx_patient_zip_code', table_name='patient_profiles')
    op.drop_index('idx_patient_insurance_provider', table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_procedure_name', table_name='procedures')
    op.drop_index('idx_procedure_category', table_name='procedures')
    op.drop_table('procedures')
    # ### end Alembic commands ###
